### ISSUE TITLE
Bold text flickering

### ISSUE THREAD

**Issue by benplumley** [olmokramer/atom-block-cursor#11]
My block cursor is causing flicker of bold text using any syntax theme that uses bold text. Pictured is Seti Monokai, but the default themes also have this problem. When the cursor is not blinking, for instance when I select text, the bold text stops flashing until the cursor starts to blink again.
![c9c2b57e2a02ff8a79bf4579ca79cd1f](https://cloud.githubusercontent.com/assets/7894368/7203268/5e87af10-e511-11e4-856d-08ec8e778863.gif)
Setting the Pulse Duration to 0 stops this from happening.

Using Atom 187, Block Cursor 12.1, Windows 8.1 Pro. Settings I've changed in Block Cursor are Blink Interval 1000 and Pulse Duration 200.

I've tried reinstalling the package and clearing my styles.less.

**Comment by olmokramer** [comment]
Hmmm that's weird, I'll take a look this weekend. In the meantime, could you upgrade your atom to the newest version and see if that helps?

**Comment by olmokramer** [comment]
And can you check if older versions of this package also suffer from this problem? You can install an arbitrary version by running `apm install block-cursor@x.x.x`

**Comment by benplumley** [comment]
Still present in Atom 192 (autoupdater hadn't seen it yet, oops). Rolling Block Cursor back to 0.12.0 fixed it in Atom 192 and Atom 187.

**Comment by olmokramer** [comment]
Ok thanks. As I said, I'll take a look this weekend, probably sunday.

**Comment by olmokramer** [comment]
A new version is up that should fix this. It adds an option, `useHardwareAcceleration`, that enables hardware acceleration of certain animations. Sadly, they cause this flickering, so you can disable them now.
