### ISSUE TITLE
No more pulsing animation for Border box??

### ISSUE THREAD

**Issue by v3ss0n** [olmokramer/atom-block-cursor#14]
Just updated to 0.12.3 but i no longer see easing pulse animation for Border box.

**Comment by v3ss0n** [comment]
Also no animation in Underline cursor too.

**Comment by v3ss0n** [comment]
I think this change breaks it : https://github.com/olmokramer/atom-block-cursor/commit/76836fdcdc8d50bac743d1197f6b71bb5d1642c2

**Comment by olmokramer** [comment]
Stupid semicolons... ;)

`v0.12.4` should fix this

**Comment by v3ss0n** [comment]
thanks , updating!

**Comment by v3ss0n** [comment]
it fixed , but a performance issue , i am creating new issue.

**Comment by v3ss0n** [comment]
Thanks a lot for very quick fixes :D . The cpu usage issues seem to be from Atom 0.194 , i had roll back to 0.12.1 to confirm and use 0.12.1 same cpu usage (10% average). it was 1-2% before.
