### ISSUE TITLE
 Back in 0.12.1 CPU usage of cursor animation is around 1-2% now 10% . 

### ISSUE THREAD

**Issue by v3ss0n** [olmokramer/atom-block-cursor#15]
After updated to 0.12.4 , the performance issue is back again.

**Comment by v3ss0n** [comment]
it seems it has to do partially with Atom 0.194 .  Even block-cursor disabled cpu usage is 4% avg.

**Comment by v3ss0n** [comment]
opened issue at atom https://github.com/atom/atom/issues/6471

**Comment by olmokramer** [comment]
Alright, I'll keep an eye on atom/atom#6471, thanks!

**Comment by olmokramer** [comment]
Hey, I was wondering if this is still an issue? On my end, things have become a _lot_ smoother with the latest Atom release (0.200.0)

**Comment by v3ss0n** [comment]
it  still have a problem. It uses up to 10% CPU when atom-block-cursor is enabled. 
it is fine when disabled.

**Comment by v3ss0n** [comment]
updated to atom latest master, right now wtihout block cursor , it only takes 1% cpu , smooth , but using block-cursor it takes up to 7-9.

**Comment by olmokramer** [comment]
Ok that's still not very good... :( Is this with `pulseDuration` set? If so, how much is it without the pulse?

**Comment by v3ss0n** [comment]
without pulse it is same as without block-cursor. Pulse duration is 2000 , same as blink Interval .

**Comment by v3ss0n** [comment]
Increasing pulse duration and blink interval does nothing.

**Comment by olmokramer** [comment]
Hmm.. Well I'm afraid there's not much I can do at this point. The animations use hardware acceleration where possible, as we've discussed in #9... If you're really bothered by the CPU usage, I'd suggest setting `pulseDuration` to `0`. Or if you have any other suggestions, please don't hesitate :)

**Comment by v3ss0n** [comment]
not really bothered at all , its quite fine so far. But i just wondering
what cause the slow down.
