### ISSUE TITLE
Loosing focus is confusing

### ISSUE THREAD

**Issue by drozzy** [olmokramer/atom-block-cursor#16]
When an editor, or panel looses focus, the cursor is not in any way affected.
In fact, it is really confusing if the focus is on the project explorer - and the cursor is still blinking in the main editor.

Looking at how emacs does it: the cursor turns into a block-cursor (hollow) if the buffer looses focus.

Thanks!

**Comment by olmokramer** [comment]
I like this idea! Thanks :)

This would require a fair amount of rewriting though, I'll basically have to add another cursor to be styled, but it allows for the opportunity to be able to style the `blink-off` and this `inactive` cursor completely independent from the normal one. 

I'll definitely add this to my to-do list, but it'll have to wait a while, I'm super busy right now.

**Comment by drozzy** [comment]
Np, good luck and thank you.

**Comment by olmokramer** [comment]
Hey I've updated the package (not published though, I'm still waiting for a [bug](https://github.com/atom/settings-view/issues/518) in atom/settings-view, that causes settings to disappear, to be fixed). But it's now possible to do what you requested. If you want to try it, you can clone the master branch of this repository into `~/.atom/packages` and reload Atom.

It requires some configuration, but the readme has an example with something similar as you requested. Let me know if you have any questions.

**Comment by olmokramer** [comment]
Hey, I've just published the new version that should make your request possible. It breaks the current configuration though, so you'll have to setup again. Please let me know what you think!
