### ISSUE TITLE
Always white in find & replace dialog

### ISSUE THREAD

**Issue by exalted** [olmokramer/atom-block-cursor#18]
I noticed cursor color is always white in dialog windows (such as find & replace) and this is a problem, because if you happend to use a light theme (such as Atom/One Light), you can’t see where your cursor is positioned at.

**Comment by olmokramer** [comment]
Hmm that's not good... Thanks for reporting :)
I'll take a look at this somewhere this weekend.

**Comment by exalted** [comment]
@olmokramer :bow:

**Comment by olmokramer** [comment]
Hey man, I'm sorry it took a bit longer, but I'm very busy right now...

Anyway, could you please tell me the settings you're using?

**Comment by exalted** [comment]
Sure.

![settings_-_atom](https://cloud.githubusercontent.com/assets/314398/7759778/b80c018a-0014-11e5-9523-567eb17255da.jpg)
![settings_-_atom](https://cloud.githubusercontent.com/assets/314398/7759784/c77a90f0-0014-11e5-8855-fde076a7785b.jpg)

``` json
  "block-cursor":
    primaryColor:
      red: 255
      green: 255
      blue: 255
      alpha: 1
    secondaryColor:
      red: 255
      green: 255
      blue: 255
      alpha: 1
    preview: "The quick brown fox jumps over the lazy dog"
    cursorLineFix: true
```

**Comment by exalted** [comment]
Although as I am thinking about this, I am not sure how could you deal with this. I guess there has to be different settings for UI theme and Syntax theme? I don’t know.

**Comment by olmokramer** [comment]
Aha! So you're using a white cursor on a dark syntax theme, but your UI is light, so it's hard to distinguish the cursor. Am I right?

**Comment by olmokramer** [comment]
Oh, stupid me, I didn't see the picture of your selected themes...

**Comment by exalted** [comment]
> Aha! So you're using a white cursor on a dark syntax theme, but your UI is light, so it's hard to distinguish the cursor. Am I right?

Correct!

> Oh, stupid me, I didn't see the picture of your selected themes...

It all right, go easy on yourself :wink:

**Comment by olmokramer** [comment]
:)

I had already planned to add a feature that adds separate customization for UI and Syntax (and others :smile:), but it might take a while as I'm really busy right now.

In the meantime, you can add the following to your `styles.less`:

``` less
atom-text-editor[mini]::shadow .cursor {
  background-color: #333!important; // or some other color
}
```

It should override this package for the editors other than the main text editor.

**Comment by exalted** [comment]
Sure, thanks.

**Comment by olmokramer** [comment]
Hey I've updated the package (not published though, I'm still waiting for a [bug](https://github.com/atom/settings-view/issues/518) in atom/settings-view, that causes settings to disappear, to be fixed).

You can now independently style the cursor in `[mini]` editors from the other ones. The readme has an example to do this.

Cheers.

**Comment by olmokramer** [comment]
You can clone the master branch of this repository into `~/.atom/packages` if you want to try it.

**Comment by exalted** [comment]
:fireworks: This is great! I will wait for the update though... Thanks!

**Comment by olmokramer** [comment]
Alright, I'll let you know when the update happens :)

**Comment by exalted** [comment]
Thanks a bunch!

**Comment by olmokramer** [comment]
Hey, I've just published the new version. Settings view still suffers from the bug where sometimes settings disappear, but I didn't want to wait anymore. It's been a few weeks, and there's not a single update to the bug... Please let me know what you think!

**Comment by olmokramer** [comment]
By the way, the new version breaks your current config, so you'll have to do the setup again. It allows for lots more flexibility though!

**Comment by exalted** [comment]
Hey @olmokramer thanks for the heads-up. I am not sure what am I supposed to do at this point. Settings have got way out of my hands, should I still keep the custom styling? :confused: 

Thanks man.

**Comment by olmokramer** [comment]
Yeah, the new configuration is a little more complicated. You can copy this into your `config.cson` (overwriting the previous config):

``` cson
  "block-cursor":
    # white cursor by default
    global:
      blinkOn:
        backgroundColor:
          red: 255
          green: 255
          blue: 255
          alpha: .4
    # dary grey cursor on [mini] editors
    mini: # cursor style name
      # select these atom-text-editors to apply this cursor type to
      selector: "atom-text-editor[mini]"
      # blinkOn style
      blinkOn:
        backgroundColor:
          red: 0
          green: 0
          blue: 0
          alpha: .4
```

This should do the trick for you. 

It works by creating a second cursor style that selects only `atom-text-editor` elements with a `mini` attribute to apply the second cursor style on. The background color will overwrite the one on the global cursor style.

There's currently an issue where the cursor _must_ be rendered above text, so cursors with a background color with an alpha of `1` will cause text under it to be unreadable, that's why both the background colors in the snippet above have such a low alpha value.

I've talked to the Atom team, and they are going to fix this issue, but might take a while. In the meantime I hope this can be sufficient for you :)

**Comment by exalted** [comment]
:beers:
