### ISSUE TITLE
Customizable width/height?

### ISSUE THREAD

**Issue by xfq** [olmokramer/atom-block-cursor#2]
Emacs can display a vertical/horizontal bar with customizable pixels wide/high. See https://www.gnu.org/software/emacs/manual/html_node/elisp/Cursor-Parameters.html . It'd be nice if `block-cursor` can customize the width/height of the cursor.

**Comment by olmokramer** [comment]
I can't change the size (i.e. width and height) of the cursor, because that would mess with Atom's cursor placement (and maybe other things as well). I can however change the thickness of the lines of the `bordered-box`, `i-beam` and `underline` cursors, so I'll add that as an option.
