### ISSUE TITLE
Not working in Atom version 0.209

### ISSUE THREAD

**Issue by mok0** [olmokramer/atom-block-cursor#21]
It appears that block-cursor stopped working after I upgraded Atom to version 0.209. Now I have no cursor at all. When I disable block-cursor I get the standard I-beam cursor :-(

**Comment by mok0** [comment]
Duplicate of issue #20.

**Comment by olmokramer** [comment]
Yes indeed duplicate of #20. I'll be closing this one and continue discussion over there. Thanks for the report though :)
