### ISSUE TITLE
Disappearing cursor

### ISSUE THREAD

**Issue by marshallbu** [olmokramer/atom-block-cursor#24]
My cursor blinks and then fades completely away...

[![Gyazo](http://i.gyazo.com/dec5010345f44bc22785c732b436b655.gif)](http://gyazo.com/dec5010345f44bc22785c732b436b655)

The more I click around, the opacity returns, but when I let it sit, it blinks and then fades away.

**Comment by olmokramer** [comment]
Hey, thanks for reporting the issue. I'm very busy right now, so I don't know when I have some time to take a look at this.

**Comment by marshallbu** [comment]
Looks like setting pulseDuration to 0 fixed it for me, I think I had it set to something weird, closing this for now, thanks!

**Comment by olmokramer** [comment]
I'm guessing you had it set to something ridiculously high (several thousands)? Can't think of another explanation that would cause this behavior. Anyway, glad to hear you solved it :)

**Comment by marshallbu** [comment]
Correcto! Lol, thanks again!
