### ISSUE TITLE
Allow higher than 500?

### ISSUE THREAD

**Issue by envygeeks** [olmokramer/atom-block-cursor#3]
The default on most Linux and OS X installs is between 1000 and 1500, can we please have a higher upper limit on the cursor blink period?

**Comment by olmokramer** [comment]
This package doesn't control the blinking period. I don't know if you can change that. Atom sets the cursor blinking period at 500ms by default. In default Atom, the blinking period is the time between the cursor becoming visible and then invisible again. With this package it is the time between `primaryColor` and `secondaryColor`.

The setting you're talking about is the `pulseDuration` of the cursor, which isn't the same as the blinking period. The `pulseDuration` is the duration of the cursor <em>animating</em> from `primaryColor` to `secondaryColor`. If I would allow you to set this higher than 500, the cursor would never fully transition to the `secondaryColor`, so then setting the `secondaryColor` would be misleading.

**Comment by envygeeks** [comment]
Fair enough, I'll fork and do it myself since I know you can set it higher than 500ms as I did it already.

**Comment by olmokramer** [comment]
I thought about it, and I could add an option to also control the blinking period. If I add that, I could also lift the limit off the pulse duration. How do I change it?

**Comment by olmokramer** [comment]
I created a new issue for this: #4

**Comment by olmokramer** [comment]
I implemented customizing the blinking interval in version `0.9.0`. Along with it I lifted the limit you're talking about. Please let me know if it works :)

**Comment by envygeeks** [comment]
:+1: on the feature but I can't see the option.

**Comment by olmokramer** [comment]
Hm... That's weird. There should be an option 'Blink Interval'. Does it work if you add this to your `config.cson`?

``` cson
  'block-cursor':
    blinkInterval: 2000
```

**Comment by envygeeks** [comment]
It worked after your last update, I could see the settings.  That is legit awesome, thank you so much!

**Comment by olmokramer** [comment]
You're welcome. Happy to help :)
