### ISSUE TITLE
How can I revert to default settings?

### ISSUE THREAD

**Issue by Saro-DA** [olmokramer/atom-block-cursor#32]
After playing around with the settings and messing some things up, I want to have the default settings back. No options for that.
But Even after completely uninstalling the block-cursor and even the atom and re-installing everything, it still keeps the settings which I had previously!
Where are the settings located?

**Comment by adamrenklint** [comment]
If you open `config.cson`, you'll find at least one entry for `"block-cursor"` - just remove this to start over. If you've added multiple cursor types, you'll need to remove them also.
