### ISSUE TITLE
No visible cursor

### ISSUE THREAD

**Issue by rollecode** [olmokramer/atom-block-cursor#35]
When activating the package, I have no visible cursor. Any conf or setting doesn't help. Is this related to the deprecated stuff?

**Comment by walter-0** [comment]
See https://github.com/olmokramer/atom-block-cursor/issues/33.

**Comment by arsari** [comment]
when the new version of the package will be publish to remove the deprecation?

**Comment by walter-0** [comment]
As soon as @olmokramer looks at his issues tab.

**Comment by adamrenklint** [comment]
Resolved https://github.com/adamrenklint/atom-block-cursor/pull/34, will be published shortly

**Comment by adamrenklint** [comment]
Published v0.13.2 that resolves this issue
