### ISSUE TITLE
Deprecated selector in `block-cursor\styles\block-cursor.less`

### ISSUE THREAD

**Issue by shaal** [olmokramer/atom-block-cursor#36]
In `block-cursor\styles\block-cursor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .cursors .cursor` => `atom-text-editor.editor .cursors .cursor`

* `atom-text-editor[mini]:not(.is-focused)::shadow .cursors .cursor` => `atom-text-editor[mini]:not(.is-focused).editor .cursors .cursor`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by adamrenklint** [comment]
Resolved https://github.com/adamrenklint/atom-block-cursor/pull/34, will be published shortly

**Comment by adamrenklint** [comment]
Published v0.13.2 that resolves this issue
