### ISSUE TITLE
Blockcursor uses up to 30% Cpu All the time.

### ISSUE THREAD

**Issue by v3ss0n** [olmokramer/atom-block-cursor#9]
Animation of block cursor shouldn't take that much CPU .

**Comment by olmokramer** [comment]
What settings are you using?

**Comment by v3ss0n** [comment]
Blink interval : 1500
Pulse Duration : 1500
Alpha : 0.5
Thickness : 4

**Comment by v3ss0n** [comment]
With css3 animations it only take up to 3% cpu .
Tested here : http://jsfiddle.net/Fy8vD/1450/

**Comment by olmokramer** [comment]
I use css3 transitions, so it should be just as performant. Also, I don't animate the opacity of the cursor, but the background/border-color. Animating opacity is handled by GPU so it's probably be smoother.

Maybe you can try the `translateZ(0)` hack on the cursors:

``` less
atom-text-editor::shadow .cursors .cursor {
  transform: translateZ(0);
}
```

**Comment by v3ss0n** [comment]
I will see but currently it takes somuch cpu with atom block cursor packag

**Comment by v3ss0n** [comment]
traslateZ(0)  makes 10% cpu. playing with Opacity is much smoother.

**Comment by olmokramer** [comment]
Ok, that's quite an improvement! I'll check if there's an easy way to animate opacity instead of background/border-color when the secondaryColorAlpha is set to 0, probably somewhere next weekend.

**Comment by olmokramer** [comment]
I made it so when `secondaryColorAlpha === 0` it will animate the opacity. When I've also fixed #10 I'll publish the new version.

**Comment by olmokramer** [comment]
New version 0.12.1 is up. Please let me know if it helps :)

**Comment by v3ss0n** [comment]
Now its awesome! default CPU usage is around 1-2% max. So its only using gpu right? very cool! Thanks alot!

**Comment by olmokramer** [comment]
Glad to hear it's fixed :) Yes, if the secondaryColor is transparent, opacity is animated instead of border/background-color, so that should be GPU.
Cheers,
